# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setMaximumSize(QtCore.QSize(600, 400))
        self.login_widget = QtWidgets.QWidget(Form)
        self.login_widget.setGeometry(QtCore.QRect(40, 110, 520, 160))
        self.login_widget.setMinimumSize(QtCore.QSize(520, 160))
        self.login_widget.setMaximumSize(QtCore.QSize(520, 160))
        self.login_widget.setToolTipDuration(-1)
        self.login_widget.setObjectName("login_widget")
        self.login_btn = QtWidgets.QPushButton(self.login_widget)
        self.login_btn.setEnabled(False)
        self.login_btn.setGeometry(QtCore.QRect(159, 107, 230, 35))
        self.login_btn.setMinimumSize(QtCore.QSize(230, 35))
        self.login_btn.setMaximumSize(QtCore.QSize(230, 35))
        self.login_btn.setStyleSheet("QPushButton{\n"
"    background-color:rgb(85, 170, 255);\n"
"    font: 10pt \"微软雅黑\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:6px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(0, 170, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:rgb(172, 172, 172);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(25, 225, 255);\n"
"}\n"
"")
        self.login_btn.setCheckable(False)
        self.login_btn.setObjectName("login_btn")
        self.antologin_checkbox = QtWidgets.QCheckBox(self.login_widget)
        self.antologin_checkbox.setGeometry(QtCore.QRect(303, 82, 87, 19))
        self.antologin_checkbox.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color:rgb(191, 197, 203);")
        self.antologin_checkbox.setObjectName("antologin_checkbox")
        self.rember_checkbox = QtWidgets.QCheckBox(self.login_widget)
        self.rember_checkbox.setEnabled(True)
        self.rember_checkbox.setGeometry(QtCore.QRect(160, 82, 87, 19))
        self.rember_checkbox.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color:rgb(191, 197, 203);")
        self.rember_checkbox.setObjectName("rember_checkbox")
        self.password_line = QtWidgets.QLineEdit(self.login_widget)
        self.password_line.setGeometry(QtCore.QRect(159, 47, 230, 30))
        self.password_line.setMinimumSize(QtCore.QSize(230, 30))
        self.password_line.setMaximumSize(QtCore.QSize(230, 30))
        self.password_line.setStyleSheet("QLineEdit{\n"
"    font-size:16px;\n"
"    border:none;\n"
"    border-bottom:1px solid lightgray;\n"
"    background-color:transparent;\n"
"    font: 10pt \"黑体\";\n"
"}\n"
"QLineEdit:hover{\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}\n"
"")
        self.password_line.setText("")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setClearButtonEnabled(True)
        self.password_line.setObjectName("password_line")
        self.name_line = QtWidgets.QComboBox(self.login_widget)
        self.name_line.setGeometry(QtCore.QRect(160, 20, 230, 30))
        self.name_line.setMinimumSize(QtCore.QSize(230, 30))
        self.name_line.setMaximumSize(QtCore.QSize(230, 30))
        self.name_line.setStyleSheet("QComboBox{\n"
"    font-size:20px;\n"
"    border:none;\n"
"    border-bottom:1px solid lightgray;\n"
"    background-color:transparent;\n"
"}\n"
"QComboBox:hover{\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QComboBox:focus{\n"
"    border-bottom:1px solid rgb(18,183,245);\n"
"}\n"
"QComboBox::drop-down{\n"
"    background-color:transparent;\n"
"    width:40px;\n"
"    height:30px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/login/下拉.png);\n"
"    width:60px;\n"
"    height:20px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    min-height:60px;\n"
"}\n"
"QComboBox QAbstractItemView:item{\n"
"    color:lightblus;\n"
"}")
        self.name_line.setEditable(True)
        self.name_line.setObjectName("name_line")
        self.name_line.addItem("")
        self.login_state = QtWidgets.QLabel(Form)
        self.login_state.setGeometry(QtCore.QRect(150, 280, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.login_state.setFont(font)
        self.login_state.setText("")
        self.login_state.setObjectName("login_state")

        self.retranslateUi(Form)
        self.name_line.editTextChanged['QString'].connect(Form.check_login)
        self.password_line.textChanged['QString'].connect(Form.check_login)
        self.login_btn.clicked.connect(Form.checked_login)
        self.antologin_checkbox.clicked['bool'].connect(Form.auto_login)
        self.rember_checkbox.clicked['bool'].connect(Form.rember_pwd)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计算登录界面"))
        self.login_btn.setText(_translate("Form", "登录"))
        self.antologin_checkbox.setText(_translate("Form", "自动登录"))
        self.rember_checkbox.setText(_translate("Form", "记住密码"))
        self.password_line.setPlaceholderText(_translate("Form", "请输入你的密码"))
        self.name_line.setItemText(0, _translate("Form", "1234567890"))
